SELECT * FROM ANSWERBOARD a ;

--UPDATE--
UPDATE ANSWERBOARD SET STEP = STEP + 1
WHERE "REF"= (SELECT "REF" FROM ANSWERBOARD a WHERE SEQ='15')
AND STEP > (SELECT STEP FROM ANSWERBOARD a2 WHERE SEQ='15');
--INSERT--
INSERT INTO ANSWERBOARD (SEQ, ID, TITLE, CONTENT, "REF", STEP, "DEPTH") 
VALUES(ANSWERBOARD_SEQ.NEXTVAL, 'TEST', 'TITLE','CONTENT',
(SELECT "REF" FROM ANSWERBOARD a WHERE SEQ='15'),
(SELECT STEP FROM ANSWERBOARD a2 WHERE SEQ='15')+1,
(SELECT "DEPTH" FROM ANSWERBOARD a3 WHERE SEQ='15')+1);

SELECT SEQ, ID, TITLE, CONTENT, STEP, DEPTH, REF, DELFLAG, REGDATE FROM ANSWERBOARD
WHERE DELFLAG='N'
ORDER BY "REF" ASC,"DEPTH" ASC, STEP DESC;

--------------------------------------
SELECT * FROM USERINFO u ;

