CREATE TABLE USERINFO(
ID VARCHAR2(20) NOT NULL,
NAME VARCHAR2(20) NOT NULL,
PASSWORD VARCHAR2(20) NOT NULL,
EMAIL VARCHAR2(20) NOT NULL,
AUTH VARCHAR2(20) NOT NULL,
DELFLAG VARCHAR2(20) NOT NULL,
JOINDATE DATE 
);

SELECT * FROM USERINFO u;

INSERT INTO USERINFO  values ('ldkkoj111', '이인환', '123456','ldkkoj777@naver.com','U','N',SYSDATE)

SELECT ID, NAME, AUTH FROM USERINFO
WHERE ID = 'ldkkoj111' AND PASSWORD='123456';