SELECT * FROM JOBS;

INSERT INTO JOBS(JOB_ID, JOB_TITLE, MIN_SALARY, MAX_SALARY)
VALUES('TEST','TEST',100,1000);

DELETE FROM JOBS WHERE JOB_ID = 'TEST1';

UPDATE JOBS SET USEAGE = 'Y';

SELECT USEAGE FROM JOBS;

SELECT CONCAT(JOB_ID,USEAGE), JOB_TITLE, MIN_SALARY, MAX_SALARY FROM JOBS;
