CREATE TABLE STARMEMBER(
  SEQ NUMBER NOT NULL,
  ID VARCHAR2(20) NOT NULL,
  PASSWORD VARCHAR2(100) NOT NULL,
  NAME VARCHAR2(50) NOT NULL,
  ADDRESS VARCHAR2(200) NOT NULL,
  PHONE VARCHAR2(20) NOT NULL,
  EMAIL VARCHAR2(100) NOT NULL,
  ENABLE CHAR(1) NOT NULL,
  "ROLE" VARCHAR2(10) NOT NULL,
  CONSTRAINT "STARMEMBER_PK" PRIMARY KEY(SEQ),
  CONSTRAINT "STARMEMBER_UL1" UNIQUE ("ID","EMAIL")
);

CREATE SEQUENCE STARMEMBER_SEQ START WITH 1 INCREMENT BY 1;

SELECT * FROM STARMEMBER ;

INSERT INTO BD.STARMEMBER
(SEQ, ID, PASSWORD, NAME, ADDRESS, PHONE, EMAIL, ENABLE, "ROLE")
VALUES(0, 'ldkkoj111', '123456', '이인환', '서울시관악구신림동', '01033097483', 'ldkkoj777@naver.com', 'Y', 'backSu');

