CREATE TABLE STARMEMBER(
  SEQ NUMBER NOT NULL,
  ID VARCHAR2(20) NOT NULL,
  PASSWORD VARCHAR2(100) NOT NULL,
  NAME VARCHAR2(50) NOT NULL,
  ADDRESS VARCHAR2(200) NOT NULL,
  PHONE VARCHAR2(20) NOT NULL,
  EMAIL VARCHAR2(100) NOT NULL,
  ENABLE CHAR(1) NOT NULL,
  "ROLE" VARCHAR2(10) NOT NULL,
  CONSTRAINT "STARMEMBER_PK" PRIMARY KEY(SEQ),
  CONSTRAINT "STARMEMBER_UL1" UNIQUE ("ID","EMAIL")
);

CREATE SEQUENCE STARMEMBER_SEQ START WITH 1 INCREMENT BY 1;

SELECT * FROM STARMEMBER ;

INSERT INTO STARMEMBER
(SEQ, ID, PASSWORD, NAME, ADDRESS, PHONE, EMAIL, ENABLE, "ROLE")
VALUES(STARMEMBER_SEQ.NEXTVAL, 'GD001', 'GD001', '수빈이', '부천', '1111', 'soo1111@naver.com', 'Y', 'ADMIN');

INSERT INTO STARMEMBER
(SEQ, ID, PASSWORD, NAME, ADDRESS, PHONE, EMAIL, ENABLE, "ROLE")
VALUES(STARMEMBER_SEQ.NEXTVAL, 'GD002', 'GD002', '정민이', '아포', '11112', 'soo2222@naver.com', 'Y', 'USER');

INSERT INTO STARMEMBER
(SEQ, ID, PASSWORD, NAME, ADDRESS, PHONE, EMAIL, ENABLE, "ROLE")
VALUES(STARMEMBER_SEQ.NEXTVAL, 'Q001', 'Q001', '정민이', '아포', '11112', 'soo2222@naver.com', 'Y', 'USER');

SELECT ID, NAME, "ROLE" 
	FROM STARMEMBER s 
	WHERE ID='GD001' AND PASSWORD ='GD001' AND ENABLE ='Y';

SELECT *
	FROM ANSWERBOARD a 
		WHERE SEQ='5';
	
SELECT a.SEQ, NVL(NAME,'GUEST') AS ID, TITLE, CONTENT,
	CASE WHEN TO_CHAR(REGDATE,'YYYY-MM-DD') <= TO_CHAR(SYSDATE, 'YYYY-MM-DD')
		THEN TO_CHAR(REGDATE,'YYYY-MM-DD hh:mi:ss') 
		ELSE TO_CHAR(REGDATE, 'YYYY-MM-DD') END AS REGDATE 
	FROM ANSWERBOARD a LEFT JOIN STARMEMBER s 
	USING(ID)
	WHERE DELFLAG ='N'
	AND "DEPTH" ='0'
	ORDER BY a.SEQ DESC;
