CREATE TABLE MEMBER(
  ID VARCHAR2(20) NOT NULL,
  PW VARCHAR2(20) NOT NULL,
  NAME VARCHAR2(20) NOT NULL,
  AUTH VARCHAR2(20) NOT NULL,
  DELFLAG VARCHAR2(20) NOT NULL,
  REFDATE DATE NOT NULL
);

SELECT * FROM MEMBER;



