CREATE TABLE BOARD(
  SEQ NUMBER PRIMARY KEY,  --seq
  EMP_CODE VARCHAR2(10), --사원번호
  TITLE VARCHAR2(100) NOT NULL,--제목
  CONTENT VARCHAR2(4000) NOT NULL,--내용
  REGDATE DATE NOT NULL,--작성날짜 
  S_COUNT NUMBER NOT NULL,--카운트
  POST_DATE DATE NOT NULL,--게시기간
  POST_USE VARCHAR2(5) NOT NULL,-- Y or N
  CONSTRAINT "BOARD_FK" FOREIGN KEY ("EMP_CODE") REFERENCES USER_INFO("EMP_CODE")
);

CREATE SEQUENCE BOARD_SEQ INCREMENT BY 1 START WITH 1;

DROP TABLE BOARD;

SELECT * FROM BOARD;

--게시글 입력 gg
INSERT INTO BOARD
(SEQ, EMP_CODE, TITLE, CONTENT, REGDATE, S_COUNT, POST_DATE, POST_USE)
VALUES(BOARD_SEQ.NEXTVAL,'SYS_45282','5월 공지사항8', '회사가 가난합니다. 휴지를 아껴써주세요.8',
SYSDATE,0,TO_CHAR(ADD_MONTHS(SYSDATE, 1), 'YYYY-MM-DD'),'Y');


--게시글 수정
UPDATE BOARD SET TITLE='4월 공지사항 수정', CONTENT='수정 회사가 가난합니다. 휴지를 아껴써주세요.' WHERE SEQ = '29' AND EMP_CODE='SYS_45282';


--게시글 삭제 
DELETE FROM BOARD WHERE SEQ = '1' AND EMP_CODE='SYS_45282';

--게시플 삭제여부 변경
UPDATE BOARD SET POST_USE ='Y' 
	WHERE SEQ IN('21','22');


--게시판 상세조회
SELECT SEQ, EMP_CODE, TITLE, CONTENT, REGDATE, S_COUNT, POST_DATE, POST_USE
	FROM BOARD 
		WHERE SEQ='21';

-- 게시판 카운트 
UPDATE BOARD SET S_COUNT = S_COUNT+1 WHERE EMP_CODE != 'SYS_45281' AND SEQ ='29';

--게시글 전체 조회 (사용자는 삭제된글 보기 불가, 관리자는 삭제된 글 보기 가능) EMP_CODE: SYS_45282 /  POST_USE : Y or N
SELECT SEQ, EMP_CODE, TITLE, CONTENT, REGDATE, S_COUNT, POST_DATE, POST_USE
 	FROM BOARD 
 	WHERE POST_USE ='N';
 
 --공지게시판 제목으로 검색
SELECT SEQ, EMP_CODE, TITLE, CONTENT, REGDATE, S_COUNT, POST_DATE, POST_USE
	FROM BOARD
		WHERE TITLE LIKE '%공지사항%';
 
 --게시기간이 끝나면 POST_USE 를 N으로 변경
 UPDATE BOARD SET POST_USE ='N' 
	WHERE TO_DATE(SYSDATE, 'YYYY-MM-DD') = TO_DATE(POST_DATE, 'YYYY-MM-DD');






