CREATE TABLE CLIENT(
  CLI_NUM VARCHAR2(100) PRIMARY KEY,
  EMP_CODE VARCHAR2(10),
  CLI_NAME VARCHAR2(100) NOT NULL,
  CLI_ADDR VARCHAR2(500) NOT NULL,
  CLI_TEL VARCHAR2(20) NOT NULL,
  CLI_AREA VARCHAR2(20) NOT NULL,
  CLI_USE VARCHAR2(5) NOT NULL,
  CONSTRAINT "CLIENT_USER_FK" FOREIGN KEY ("EMP_CODE") REFERENCES USER_INFO("EMP_CODE")
);

SELECT * FROM CLIENT;

DROP TABLE CLIENT;


--(일반) 거래처 정보 전체 조회
SELECT CLI_NUM, EMP_CODE, CLI_NAME, CLI_ADDR, CLI_TEL, CLI_AREA
 	FROM CLIENT ;
 		
	 
--(일반) 거래처 상세조회 -> 계약 내용 포함
SELECT c.CLI_NUM, c.EMP_CODE, c.CLI_NAME, c.CLI_ADDR, c.CLI_TEL,cd.RATE,cg.G_NAME,gd.RATE AS G_CODE,
 CASE WHEN SYSDATE > c2.CT_START AND SYSDATE <c2.CT_END THEN '진행중' 
 WHEN SYSDATE < c2.CT_START THEN '대기중'
 WHEN SYSDATE > c2.CT_END THEN '종료'
 END AS STATUS,TRUNC(TO_NUMBER(TO_CHAR(TO_DATE(CT_END,'yyyy-mm-dd')-TO_DATE(CT_START,'yyyy-mm-dd')))/365) CT_DATE_YEAR_SUM, c2.CT_START ,c2.CT_END
	FROM CLIENT c
		JOIN CONTRACT_MANAGEMENT cm 
		ON c.CLI_NUM = cm.CLI_NUM 
	    JOIN CONTRACT c2 
	    ON c2.CTM_CODE =cm.CTM_CODE 
		JOIN CLIENT_DISCOUNT cd 
		ON c2.DCODE_CLIENT = cd.DCODE_CLIENT 
		JOIN CONTRACT_GOODS cg 
		ON c2.CT_CODE = cg.CT_CODE 
		JOIN INVENTORY_GOODS ig 
		ON cg.G_CODE = ig.G_CODE 
		JOIN GOODS_DISCOUNT gd 
		ON ig.DCODE_GOODS = gd.DCODE_GOODS
		WHERE c.CLI_NUM='380-75-10619'
		ORDER BY gd.RATE DESC;
  		   
--(일반) 거래처 정보 삭제 (delflag동작)
	UPDATE CLIENT SET CLI_USE ='N' 
	WHERE CLI_NUM='380-75-10619';

--(일반) 거래처 정보 수정
UPDATE CLIENT SET CLI_TEL ='02-623-2112', CLI_ADDR='서울특별시 관악구 낙성대역길 35, 1층 (봉천동)' WHERE CLI_NUM = '380-75-10619';

--(일반) 거래처 업체명으로 검색
SELECT CLI_NUM, EMP_CODE, CLI_NAME, CLI_ADDR, CLI_TEL, CLI_AREA
	FROM CLIENT
		WHERE CLI_NAME LIKE '%소소한%';


-- 계약서 추가 시 TRIGGER 

--거래처 등록
INSERT INTO CLIENT
(CLI_NUM, EMP_CODE, CLI_NAME, CLI_ADDR, CLI_TEL)
VALUES('999-99-99999', 'CAD_23156', '카페이름', '카페상세주소', '거래처 전화번호');
SELECT * FROM CLIENT;

--계약관리 등록
INSERT INTO CONTRACT_MANAGEMENT
(CTM_CODE, CLI_NUM, STATUS, CT_DATE_YEAR_SUM)
VALUES('CM'||TO_CHAR(2403+CONTRACT_MANAGEMENT_SEQ.NEXTVAL), '999-99-99999', NULL, 0);

--계약 등록
INSERT INTO CONTRACT
(CT_CODE, CTM_CODE, DCODE_CLIENT, DU_PRICE, DU_DATE, CT_START, CT_END)
VALUES(11438+CONTRACT_SEQ.NEXTVAL, 'CM'||TO_CHAR(2403+CONTRACT_MANAGEMENT_SEQ.CURRVAL), 'C01', 0, '2022-06-26', '2022-05-26', '2025-05-26');

--계약상품등록
INSERT INTO ADMIN.CONTRACT_GOODS
(SEQ, CT_CODE, G_CODE, G_NAME, G_PRICE, DU_CNT)
VALUES(33074+CONTRACT_GOODS_SEQ.NEXTVAL, 11438+CONTRACT_SEQ.CURRVAL,
'D010', '케냐AA', 20000, 10);

--재고상품 업데이트(기존쿼리 재고 업데이트 쿼리 실행)
UPDATE INVENTORY_GOODS SET IV_CNT=IV_CNT+10 WHERE G_CODE='D010'

--재고관리 등록
SELECT * FROM INVENTORY_MANAGEMENT im ORDER BY SEQ DESC;
INSERT INTO ADMIN.INVENTORY_MANAGEMENT
(SEQ, EMP_CODE, G_CODE, G_NAME, IN_DATE, IN_CNT)
VALUES(33074+INVENMANAGE_SEQ.NEXTVAL, 'IAD_13397', 'D010', '케냐AA', '2022-06-26', 10);
	


CREATE TABLE CONTRACT_GOODS AS
			SELECT * FROM CONTRACT_GOODS;
		
SELECT * FROM CONTRACT_GOODS;

