CREATE TABLE INVENTORY_GOODS(
  G_CODE VARCHAR2(20) PRIMARY KEY,
  DCODE_GOODS VARCHAR2(20),
  G_NAME VARCHAR2(100) NOT NULL,
  IV_CNT NUMBER,
  G_KG VARCHAR2(10) NOT NULL,
  G_COUNTRY VARCHAR2(30) NOT NULL,
  G_CONTENT VARCHAR2(30) NOT NULL,
  G_AMOUNT VARCHAR2(10) NOT NULL,
  CONSTRAINT "INVENTORY_GOODS_FK" FOREIGN KEY ("DCODE_GOODS") REFERENCES GOODS_DISCOUNT("DCODE_GOODS")
);

SELECT * FROM INVENTORY_GOODS ig;

--출고업데이트(하루에 한번 해당하는 날짜에 해당하는 상품의 총합계를 빼준다.)
UPDATE INVENTORY_GOODS ig SET IV_CNT =IV_CNT-
(SELECT MINUS_CNT FROM 
(SELECT cg.G_CODE,SUM(DU_CNT) AS MINUS_CNT
FROM CONTRACT c 
	JOIN CONSTRACT_GOODS cg
	ON c.CT_CODE = cg.CT_CODE 
	JOIN INVENTORY_GOODS ig 
	ON cg.G_CODE = ig.G_CODE
WHERE TO_CHAR(SYSDATE,'DD')=TO_CHAR(c.DU_DATE,'DD')
GROUP BY cg.G_CODE) mg
WHERE ig.G_CODE=mg.G_CODE);


-- 입고업데이트(매월 1일마다 실행)
UPDATE INVENTORY_GOODS ig SET IV_CNT=
(SELECT PLUS_CNT
FROM 
(SELECT cg.G_CODE ,SUM(cg.DU_CNT) PLUS_CNT
FROM CONTRACT c 
	JOIN CONTRACT_GOODS cg
	ON c.CT_CODE = cg.CT_CODE 
	JOIN INVENTORY_GOODS ig 
	ON cg.G_CODE = ig.G_CODE
	WHERE CT_START < SYSDATE
	AND CT_END > SYSDATE
	GROUP BY cg.G_CODE) mg
	WHERE ig.G_CODE=mg.G_CODE);
	
--재고테이블
SELECT ig.G_CODE,
	CASE WHEN ig.G_CODE = FIRST_VALUE(ig.G_CODE) OVER() THEN 'G02' ELSE 'G01' END AS DCODE_GOODS,IV_CNT,
	ig.G_NAME, ig.G_KG, ig.G_COUNTRY, ig.G_CONTENT, ig.G_DATE, ig.G_AMOUNT
	FROM CONTRACT c 
	JOIN CONSTRACT_GOODS cg
	ON c.CT_CODE = cg.CT_CODE 
	JOIN INVENTORY_GOODS ig 
	ON cg.G_CODE = ig.G_CODE
	JOIN GOODS_DISCOUNT gd 
	ON ig.DCODE_GOODS = gd.DCODE_GOODS 
			WHERE CT_START < SYSDATE
			AND CT_END > SYSDATE;


--계약테이블
SELECT c.CT_CODE,c.CTM_CODE, c.DCODE_CLIENT,SUM(cg.G_PRICE*cg.DU_CNT) DU_PRICE,SUM(cg.G_PRICE*cg.DU_CNT-cg.G_PRICE*cg.DU_CNT*gd.RATE) PRE_SUM , SUM(cg.G_PRICE*cg.DU_CNT-cg.G_PRICE*cg.DU_CNT*(gd.RATE+cd.RATE)) SUM_PRICE, c.DU_DATE, c.CT_START, c.CT_END
FROM CONTRACT c 
JOIN CONSTRACT_GOODS cg
ON c.CT_CODE = cg.CT_CODE 
JOIN INVENTORY_GOODS ig 
ON cg.G_CODE = ig.G_CODE
JOIN GOODS_DISCOUNT gd 
ON ig.DCODE_GOODS = gd.DCODE_GOODS
JOIN CLIENT_DISCOUNT cd 
ON cd.DCODE_CLIENT = c.DCODE_CLIENT
GROUP BY (c.CT_CODE, c.CTM_CODE, c.DCODE_CLIENT, c.DU_DATE, c.CT_START, c.CT_END);

UPDATE INVENTORY_GOODS ig 
SET DCODE_GOODS='G02' 
WHERE ig.G_CODE = (SELECT DISTINCT FIRST_VALUE(ig2.G_CODE) OVER() FROM INVENTORY_GOODS ig2);


--입고,출고 날짜 및 개수
SELECT cg.G_CODE ,cg.G_NAME ,TRUNC(c.CT_START,'MM'),DU_CNT IN_CNT
FROM CONTRACT c 
JOIN CONSTRACT_GOODS cg
ON c.CT_CODE = cg.CT_CODE 
JOIN INVENTORY_GOODS ig 
ON cg.G_CODE = ig.G_CODE
FULL JOIN INVENTORY_MANAGEMENT im
ON im.G_CODE = ig.G_CODE;


