--220303 답변형 게시판 쿼리테스트
CREATE TABLE ANSWERBOARD(
	SEQ NUMBER,
	ID VARCHAR2(30) NOT NULL,
	TITLE VARCHAR2(200) NOT NULL,
	CONTENT VARCHAR2(1000),
	REF NUMBER NOT NULL,
	STEP NUMBER NOT NULL,
	DEPTH NUMBER NOT NULL,
	DELFLAG CHAR(1) DEFAULT 'N',
	REGDATE DATE DEFAULT SYSDATE
);

CREATE SEQUENCE ANSWERBOARD_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

ALTER TABLE ANSWERBOARD ADD CONSTRAINT ANSWERBOARD_PK PRIMARY KEY (SEQ);

DROP SEQUENCE ANSWERBOARD_SEQ ;

SELECT ANSWERBOARD_SEQ.CURRVAL 
	FROM DUAL;

SELECT ANSWERBOARD_SEQ.NEXTVAL 
	FROM DUAL;

--ROOT 글 입력
INSERT INTO ANSWERBOARD (SEQ,ID, TITLE, CONTENT, "REF",STEP, "DEPTH")
	VALUES (ANSWERBOARD_SEQ.NEXTVAL, 'Q001', '첫번째 새글', '새글을 작성해 봅니다.', 
			(SELECT NVL(MAX(REF),0)+1 FROM ANSWERBOARD a2) , 
			0, 0);

--ROOT 조회(전체)
SELECT SEQ ,ID ,TITLE , "REF" , STEP , "DEPTH" , DELFLAG ,REGDATE 
    FROM ANSWERBOARD a 
    ORDER BY REF DESC, STEP ASC;

--글 상세
SELECT SEQ ,ID ,TITLE , CONTENT , REGDATE 
    FROM ANSWERBOARD a 
    ORDER BY REF DESC, STEP ASC;   
   
--답글 입력(Step 증가)
 UPDATE ANSWERBOARD SET STEP = STEP + 1 
 	WHERE "REF" = (SELECT "REF" FROM ANSWERBOARD a4 WHERE SEQ = 2)
 		AND STEP > (SELECT STEP FROM ANSWERBOARD a5 WHERE SEQ = 2);

--답글 입력(INSERT)
INSERT INTO ANSWERBOARD (SEQ, ID, TITLE, CONTENT, "REF", STEP,"DEPTH")
                    VALUES(ANSWERBOARD_SEQ.NEXTVAL,'Q002','답글2 입니다.','답글2 달아요',
                    (SELECT REF FROM ANSWERBOARD a WHERE SEQ='2'),
                    (SELECT STEP FROM ANSWERBOARD a2 WHERE SEQ='2')+1,
                    (SELECT DEPTH FROM ANSWERBOARD a3 WHERE SEQ='2')+1
           	);
--글 삭제(UPDATE DELFALG = Y)
UPDATE ANSWERBOARD SET DELFLAG ='Y'
	WHERE SEQ ='1';
           
--글 수정
UPDATE ANSWERBOARD SET CONTENT = '수정된 내용'
	WHERE SEQ = '3';

--3) 시나리오 테스트 답글 달기
SELECT SEQ, ID, CASE DELFLAG WHEN 'N' THEN LPAD(' ',"DEPTH"*10)||TITLE ELSE '삭제된 글입니다' END TITLE , REGDATE 
	FROM ANSWERBOARD a 
	ORDER BY REF DESC, STEP ; 
	
SELECT SEQ,ID, TITLE, CONTENT , REGDATE 
	FROM ANSWERBOARD a 
	WHERE SEQ = 5;
	
UPDATE ANSWERBOARD SET STEP = STEP + 1
	WHERE REF = (SELECT "REF" FROM ANSWERBOARD a WHERE SEQ='5')
	AND STEP > (SELECT STEP FROM ANSWERBOARD a2 WHERE SEQ='5');
	
INSERT INTO ANSWERBOARD (SEQ, ID, 
							TITLE, CONTENT, 
							"REF", STEP, "DEPTH")
	VALUES (ANSWERBOARD_SEQ.NEXTVAL, 'Q111',
			'답글 작성 시나리오','SEQ 5번의 글에 답글을 작성', 
			(SELECT "REF" FROM ANSWERBOARD a WHERE SEQ = '5'),(SELECT STEP +1 FROM ANSWERBOARD a2 WHERE SEQ = '5'),
			(SELECT "DEPTH"+1 FROM ANSWERBOARD a3 WHERE SEQ = '5'));
			
CREATE TABLE ANSWERBOARD_TEMP AS SELECT * FROM ANSWERBOARD a ;

	
SELECT SEQ, CONTENT 
	FROM ANSWERBOARD a
	WHERE SEQ = 28;