CREATE TABLE BOARD(
  SEQ NUMBER PRIMARY KEY,  
  EMP_CODE VARCHAR2(10),
  TITLE VARCHAR2(100) NOT NULL,
  CONTENT VARCHAR2(4000) NOT NULL,
  REGDATE DATE NOT NULL,
  S_COUNT NUMBER NOT NULL,
  POST_DATE DATE NOT NULL,
  POST_USE VARCHAR2(5) NOT NULL,
  CONSTRAINT "BOARD_FK" FOREIGN KEY ("EMP_CODE") REFERENCES USER_INFO("EMP_CODE")
);

DROP TABLE BOARD;

SELECT * FROM BOARD;

CREATE SEQUENCE BOARD_SEQ INCREMENT BY 1 START WITH 1;

INSERT INTO GD.BOARD
(SEQ, EMP_CODE, TITLE, CONTENT, REGDATE, S_COUNT, POST_DATE, POST_USE)
VALUES(BOARD_SEQ.NEXTVAL,'SYS_45282','5월 공지사항', '회사가 가난합니다. 휴지를 아껴써주세요.',SYSDATE, 0,TO_CHAR(ADD_MONTHS(TO_DATE(SYSDATE, 'YYYY-MM-DD HH24:MI:SS'), 1), 'YYYY-MM-DD'),'Y');
/*
 * 이슈사항 > 게시기간이 끝나면 POST_USE 를 N으로 바꾸는 건에 대하여...
 */

