CREATE TABLE CLIENT(
  CLI_NUM VARCHAR2(100) PRIMARY KEY,
  EMP_CODE VARCHAR2(10),
  CLI_NAME VARCHAR2(100) NOT NULL,
  CLI_ADDR VARCHAR2(500) NOT NULL,
  CLI_TEL VARCHAR2(20) NOT NULL,
  CLI_AREA VARCHAR2(20) NOT NULL,
  CONSTRAINT "CLIENT_USER_FK" FOREIGN KEY ("EMP_CODE") REFERENCES USER_INFO("EMP_CODE")
);

SELECT * FROM CLIENT;

DROP TABLE CLIENT;

