CREATE TABLE CONSTRACT_GOODS(
  SEQ NUMBER PRIMARY KEY,
  CT_CODE VARCHAR2(20) NOT NULL,
  G_CODE VARCHAR2(20) NOT NULL,
  G_NAME VARCHAR2(100) NOT NULL,
  G_PRICE NUMBER NOT NULL,
  DU_CNT NUMBER
);
 
 
SELECT * FROM CONSTRACT_GOODS;

DROP TABLE CONSTRACT_GOODS;

