CREATE TABLE CONSTRACT_GOODS(
  SEQ NUMBER PRIMARY KEY,
  G_NAME VARCHAR(20) NOT NULL,
  DU_CNT NUMBER NOT NULL,
  G_PRICE NUMBER NOT NULL
);
 
 
SELECT * FROM CONSTRACT_GOODS;

DROP TABLE CONSTRACT_GOODS;

