CREATE TABLE CONTRACT(
  CT_CODE VARCHAR2(20) PRIMARY KEY,
  DCODE_CLIENT VARCHAR2(20),
  DU_PRICE NUMBER ,
  DU_DATE DATE NOT NULL,
  CT_START DATE NOT NULL,
  CT_END DATE NOT NULL,
  PRE_SUM NUMBER,
  SUM_PRICE NUMBER,
  CONSTRAINT "DCODE_CLIENT_CON_FK" FOREIGN KEY ("DCODE_CLIENT") REFERENCES CLIENT_DISCOUNT("DCODE_CLIENT")
);
 
 
SELECT * FROM CONTRACT;

DROP TABLE CONTRACT;

INSERT INTO GD.CONTRACT
(CT_CODE, DCODE_CLIENT, DU_PRICE, DU_DATE, CT_START, CT_END, PRE_SUM, SUM_PRICE)
VALUES(0, '', 0, '', '', '', 0, 0);

