CREATE TABLE CONTRACT_MANAGEMENT(
  CT_CODE NUMBER PRIMARY KEY,
  CLI_NUM VARCHAR(100),
  EMP_CODE VARCHAR(10),
  STATUS VARCHAR(10) NOT NULL,
  CT_DATE_SUM DATE NOT NULL,
  CONSTRAINT "CLI_NUM_FK" FOREIGN KEY ("CLI_NUM") REFERENCES CLIENT("CLI_NUM")
);
 
 
SELECT * FROM CONTRACT_MANAGEMENT;



DROP TABLE CONTRACT_MANAGEMENT;

