CREATE TABLE CONTRACT(
  CT_CODE NUMBER ,
  DCODE_CLIENT NUMBER NOT NULL,
  DU_PRICE NUMBER NOT NULL,
  DU_DATE DATE NOT NULL,
  CT_START DATE NOT NULL,
  CT_END DATE NOT NULL,
  PRE_SUM NUMBER,
  SUM_PRICE NUMBER,
  CONSTRAINT "CT_CODE_CON_FK" FOREIGN KEY ("CT_CODE") REFERENCES CONTRACT_MANAGEMENT("CT_CODE"),
  CONSTRAINT "DCODE_CLIENT_CON_FK" FOREIGN KEY ("DCODE_CLIENT") REFERENCES CLIENT_DISCONT("DCODE_CLIENT"),
  CONSTRAINT "CONTRACT_PK" PRIMARY KEY ("CT_CODE")
);
 
 
SELECT * FROM CONTRACT;

DROP TABLE CONTRACT;

