CREATE TABLE INVENTORY_GOODS(
  G_CODE VARCHAR2(20) PRIMARY KEY,
  CT_CODE VARCHAR2(20) NOT NULL,
  DCODE_GOODS VARCHAR2(20) ,
  G_NAME VARCHAR2(100) NOT NULL,
  IV_CNT NUMBER,
  G_KG VARCHAR2(10) NOT NULL,
  G_COUNTRY VARCHAR2(30) NOT NULL,
  G_CONTENT VARCHAR2(30) NOT NULL,
  G_DATE VARCHAR2(50) NOT NULL,
  G_AMOUNT VARCHAR2(10) NOT NULL,
  CONSTRAINT "INVENTORY_GOODS_FK" FOREIGN KEY ("DCODE_GOODS") REFERENCES GOODS_DISCOUNT("DCODE_GOODS")
);
 
 
SELECT c.CT_CODE,cg.G_NAME
FROM CONSTRACT_GOODS cg, CONTRACT c 
WHERE SYSDATE > TO_DATE(c.CT_START)
AND SYSDATE < TO_DATE(c.CT_END)
GROUP BY G_NAME ;

DROP TABLE INVENTORY_GOODS;

SELECT * 
FROM CONTRACT c 
JOIN CONSTRACT_GOODS cg 
ON c.CT_CODE = cg.CT_CODE;
SELECT * 
FROM 
(SELECT *
  FROM CONTRACT c 
    JOIN CONSTRACT_GOODS cg
      ON c.CT_CODE = cg.CT_CODE) ccg
    JOIN INVENTORY_GOODS ig
      ON ccg.CT_CODE = ig.CT_CODE;


