CREATE TABLE INVENTORY_GOODS(
  G_CODE VARCHAR2(20) PRIMARY KEY,
  DCODE_GOODS VARCHAR2(20),
  G_NAME VARCHAR2(100) NOT NULL,
  IV_CNT NUMBER,
  G_KG VARCHAR2(10) NOT NULL,
  G_COUNTRY VARCHAR2(30) NOT NULL,
  G_CONTENT VARCHAR2(30) NOT NULL,
  G_DATE VARCHAR2(50) NOT NULL,
  G_AMOUNT VARCHAR2(10) NOT NULL,
  CONSTRAINT "INVENTORY_GOODS_FK" FOREIGN KEY ("DCODE_GOODS") REFERENCES GOODS_DISCOUNT("DCODE_GOODS")
);

ALTER TABLE INVENTORY_GOODS ADD IV_CNT NUMBER;
 
SELECT * FROM INVENTORY_GOODS ig ;

DROP TABLE INVENTORY_GOODS;

UPDATE INVENTORY_GOODS SET DCODE_GOODS ='G01'; 

--재고테이블
SELECT ig.G_CODE,
CASE WHEN ig.G_CODE = FIRST_VALUE(ig.G_CODE) OVER()
THEN 'G02'
ELSE 'G01'
END AS DCODE_GOODS,
SUM(DU_CNT) IV_CNT,
ig.G_NAME, ig.G_KG, ig.G_COUNTRY, ig.G_CONTENT, ig.G_DATE, ig.G_AMOUNT 
FROM CONTRACT c 
JOIN CONSTRACT_GOODS cg
ON c.CT_CODE = cg.CT_CODE 
JOIN INVENTORY_GOODS ig 
ON cg.G_CODE = ig.G_CODE
JOIN GOODS_DISCOUNT gd 
ON ig.DCODE_GOODS = gd.DCODE_GOODS 
WHERE CT_START < SYSDATE
AND CT_END > SYSDATE
GROUP BY (ig.G_CODE,ig.DCODE_GOODS, ig.G_NAME, ig.G_KG, ig.G_COUNTRY, ig.G_CONTENT, ig.G_DATE, ig.G_AMOUNT)
ORDER BY IV_CNT;


--계약테이블
SELECT c.CT_CODE,c.CTM_CODE, c.DCODE_CLIENT,SUM(cg.G_PRICE*cg.DU_CNT) DU_PRICE,SUM(cg.G_PRICE*cg.DU_CNT-cg.G_PRICE*cg.DU_CNT*gd.RATE) PRE_SUM , SUM(cg.G_PRICE*cg.DU_CNT-cg.G_PRICE*cg.DU_CNT*(gd.RATE+cd.RATE)) SUM_PRICE, c.DU_DATE, c.CT_START, c.CT_END
FROM CONTRACT c 
JOIN CONSTRACT_GOODS cg
ON c.CT_CODE = cg.CT_CODE 
JOIN INVENTORY_GOODS ig 
ON cg.G_CODE = ig.G_CODE
JOIN GOODS_DISCOUNT gd 
ON ig.DCODE_GOODS = gd.DCODE_GOODS
JOIN CLIENT_DISCOUNT cd 
ON cd.DCODE_CLIENT = c.DCODE_CLIENT
GROUP BY (c.CT_CODE, c.CTM_CODE, c.DCODE_CLIENT, c.DU_DATE, c.CT_START, c.CT_END);


UPDATE INVENTORY_GOODS ig 
SET DCODE_GOODS='G02' 
WHERE ig.G_CODE = (SELECT DISTINCT FIRST_VALUE(ig2.G_CODE) OVER() FROM INVENTORY_GOODS ig2);


--입고,출고 날짜 및 개수
SELECT cg.G_CODE ,cg.G_NAME ,TRUNC(c.CT_START,'MM'),DU_CNT IN_CNT
,c.DU_DATE OUT_DATE, DU_CNT OUT_CNT
FROM CONTRACT c 
JOIN CONSTRACT_GOODS cg
ON c.CT_CODE = cg.CT_CODE 
JOIN INVENTORY_GOODS ig 
ON cg.G_CODE = ig.G_CODE;

UPDATE CONSTRACT_GOODS SET DU_CNT=0 WHERE SYSDATE=OUT_DATE

--재고수량
UPDATE INVENTORY_GOODS ig
SET IV_CNT = (SELECT G_CODE,SUM(DU_CNT) FROM CONSTRACT_GOODS gs GROUP BY G_CODE)
WHERE ig.G_CODE = gs.G_CODE;
SELECT G_CODE ,SUM(DU_CNT) FROM CONSTRACT_GOODS
GROUP BY G_CODE;
