CREATE TABLE INVENTORY_MANAGEMENT(
  SEQ NUMBER,
  G_CODE VARCHAR2(20),
  EMP_CODE VARCHAR2(10) NOT NULL,
  IN_DATE DATE NOT NULL,
  OUT_DATE DATE NOT NULL,
  IN_CNT NUMBER NOT NULL,
  OUT_CNT NUMBER NOT NULL,
  CONSTRAINT "G_CODE_FK" FOREIGN KEY ("G_CODE") REFERENCES INVENTORY_GOODS("G_CODE"),
  CONSTRAINT "EMP_CODE_FK" FOREIGN KEY ("EMP_CODE") REFERENCES USER_INFO("EMP_CODE"),
  CONSTRAINT "INVENTORY_MANAGEMENT_PK" PRIMARY KEY ("SEQ","G_CODE")
);
 
 
SELECT * FROM INVENTORY_MANAGEMENT;

DROP TABLE INVENTORY_MANAGEMENT;

