CREATE TABLE INVENTORY_GOODS(
  G_CODE VARCHAR2(20) PRIMARY KEY,
  DCODE_GOODS VARCHAR2(20) NOT NULL,
  G_NAME VARCHAR2(100) NOT NULL,
  IV_CNT NUMBER,
  G_COUNTRY VARCHAR2(30) NOT NULL,
  G_CONTENT VARCHAR2(30) NOT NULL,
  G_DATE VARCHAR2(50) NOT NULL,
  G_CAPACITY VARCHAR2(10) NOT NULL,
  G_AMOUNT VARCHAR2(10) NOT NULL,
  CONSTRAINT "INVENTORY_GOODS_FK" FOREIGN KEY ("DCODE_GOODS") REFERENCES GOODS_DISCOUNT("DCODE_GOODS")
);
 
 
SELECT * FROM INVENTORY_GOODS;

DROP TABLE INVENTORY_GOODS;