CREATE TABLE INVENTORY_MANAGEMENT(
  SEQ NUMBER PRIMARY KEY,
  EMP_CODE VARCHAR2(10),
  G_CODE VARCHAR2(20) NOT NULL,
  G_NAME VARCHAR2(100) NOT NULL,
  IN_DATE DATE NOT NULL,
  IN_CNT NUMBER,
  CONSTRAINT "G_CODE_FK" FOREIGN KEY ("G_CODE") REFERENCES INVENTORY_GOODS("G_CODE"),
  CONSTRAINT "EMP_CODE_FK" FOREIGN KEY ("EMP_CODE") REFERENCES USER_INFO("EMP_CODE")
);
 
CREATE SEQUENCE INVENMANAGE_SEQ INCREMENT BY 1 START WITH 1;
 
SELECT * FROM INVENTORY_MANAGEMENT;

DROP TABLE INVENTORY_MANAGEMENT;

SELECT im.SEQ,cg.G_CODE ,cg.G_NAME ,im.EMP_CODE,TRUNC(c.CT_START,'MM'),DU_CNT IN_CNT
FROM CONTRACT c
JOIN CONSTRACT_GOODS cg
ON c.CT_CODE = cg.CT_CODE 
JOIN INVENTORY_GOODS ig 
ON cg.G_CODE = ig.G_CODE
JOIN INVENTORY_MANAGEMENT im
ON im.G_CODE = ig.G_CODE 
JOIN USER_INFO ui 
ON ui.EMP_CODE = im.EMP_CODE;
