CREATE TABLE GOODS(
  G_CODE VARCHAR2(20) PRIMARY KEY,
  G_NAME VARCHAR2(100) NOT NULL,
  G_PRICE NUMBER NOT NULL,
  G_KG VARCHAR2(10) NOT NULL,
  G_COUNTRY VARCHAR2(30) NOT NULL,
  G_CONTENT VARCHAR2(30) NOT NULL,
  G_DATE VARCHAR2(50) NOT NULL,
  G_AMOUNT VARCHAR2(10) NOT NULL
);

SELECT * FROM GOODS;


