CREATE TABLE USER_INFO(
	EMP_CODE VARCHAR2(10) PRIMARY KEY,
	AREA_CODE VARCHAR2(10),
	EMP_NAME VARCHAR2(10) NOT NULL,
	EMP_PW VARCHAR2(20) NOT NULL,
	EMP_GENDER VARCHAR2(6) NOT NULL,
	EMP_USE VARCHAR2(2) NOT NULL,
	EMP_IMG BLOB,
	CONSTRAINT "USER_INFO_FK" FOREIGN KEY ("AREA_CODE") REFERENCES LOCATION("AREA_CODE")
);


SELECT * FROM USER_INFO;

DROP TABLE USER_INFO;

INSERT INTO GD.USER_INFO
(EMP_CODE, AREA_CODE, EMP_NAME, EMP_PW, EMP_GENDER, EMP_USE, EMP_IMG)
VALUES('SYS_45282', NULL, '노수빈', 'subin1234', '여자', 'Y', EMPTY_BLOB());

INSERT INTO GD.USER_INFO
(EMP_CODE, AREA_CODE, EMP_NAME, EMP_PW, EMP_GENDER, EMP_USE, EMP_IMG)
VALUES('CAD_33873', 'LC01', '이인환', 'inhwan1234', '남자', 'Y', EMPTY_BLOB());

INSERT INTO GD.USER_INFO
(EMP_CODE, AREA_CODE, EMP_NAME, EMP_PW, EMP_GENDER, EMP_USE, EMP_IMG)
VALUES('CAD_23156', 'LC04', '정상수', 'sangsoo1234', '남자', 'Y', EMPTY_BLOB());

INSERT INTO GD.USER_INFO
(EMP_CODE, AREA_CODE, EMP_NAME, EMP_PW, EMP_GENDER, EMP_USE, EMP_IMG)
VALUES('CAD_71542', 'LC02', '김대규', 'deakyu1234', '여자', 'Y', EMPTY_BLOB());

INSERT INTO GD.USER_INFO
(EMP_CODE, AREA_CODE, EMP_NAME, EMP_PW, EMP_GENDER, EMP_USE, EMP_IMG)
VALUES('CAD_98374', 'LC05', '강동원', 'dongwon1234', '남자', 'Y', EMPTY_BLOB());

INSERT INTO GD.USER_INFO
(EMP_CODE, AREA_CODE, EMP_NAME, EMP_PW, EMP_GENDER, EMP_USE, EMP_IMG)
VALUES('IAD_13397', null, '김지수', 'jisoo1234', '여자', 'Y', EMPTY_BLOB());