SELECT RNUM, PLAYER_ID  , E_PLAYER_NAME , NICKNAME 
FROM (SELECT ROW_NUMBER() OVER(ORDER BY PLAYER_ID) AS RNUM, PLAYER_ID ,PLAYER_NAME ,  E_PLAYER_NAME , NICKNAME
	FROM PLAYER p) 
	WHERE RNUM>0 AND ROWNUM<=10;