-- 3) 시나리오 테스트 답글달기

SELECT SEQ, ID, CASE DELFLAG WHEN 'N' THEN LPAD(' ',"DEPTH"*10) || TITLE ELSE '삭제된 글입니다' END TITLE, REDATE 
FROM ANSWERBOARD a 
ORDER BY REF DESC, STEP;

SELECT SEQ, ID, TITLE, CONTENT, REDATE 
FROM ANSWERBOARD a 
WHERE SEQ = '5';

UPDATE ANSWERBOARD SET STEP = STEP+1
WHERE REF = (SELECT REF FROM ANSWERBOARD a WHERE SEQ = '5')
AND STEP > (SELECT STEP FROM ANSWERBOARD a2 WHERE SEQ = '5');

INSERT INTO ANSWERBOARD (SEQ, ID, TITLE, CONTENT, "REF", STEP, "DEPTH")
VALUES (ANSWERBOARD_SEQ.NEXTVAL, 'Q111','답글 작성 시나리오' ,'SEQ 5의 글에 답글을 작성', 
(SELECT REF FROM ANSWERBOARD a WHERE SEQ = '5'),(SELECT STEP +1 FROM ANSWERBOARD a2 WHERE SEQ='5'),
(SELECT "DEPTH"+1 FROM ANSWERBOARD a3 WHERE SEQ ='5'));