--테이블

CREATE TABLE GDUESR(
  ID VARCHAR2(20) PRIMARY KEY,
  PASSWORD VARCHAR2(500),
  NAME VARCHAR2(50) NOT NULL,
  REGDATE DATE NOT NULL 
  );

INSERT INTO GDUESR
(ID, PASSWORD, NAME, REGDATE)
VALUES('ldkkoj111', '123456', '이인환', '19970919');

SELECT * FROM GDUESR;

  
