--테이블
CREATE TABLE GDUSER(
  ID VARCHAR2(20) PRIMARY KEY,
  PASSWORD VARCHAR2(500),
  NAME VARCHAR2(50) NOT NULL,
  REGDATE DATE NOT NULL 
  );


INSERT INTO GDUSER
(ID, PASSWORD, NAME, REGDATE)
VALUES('ldkkoj111', '123456', '이인환', SYSDATE);

INSERT INTO GDUSER
(ID, PASSWORD, NAME, REGDATE)
VALUES('rladndus3', '123456', '김우연', SYSDATE);


SELECT * FROM GDUSER;

SELECT COUNT(*)
  FROM GDUSER
  WHERE ID='ldkkoj111' AND PASSWORD='123456';
