CREATE TABLE CLIENT_DISCOUNT(
	DCODE_CLIENT VARCHAR2(20) PRIMARY KEY,
	RATE NUMBER NOT NULL
);

SELECT * FROM CLIENT_DISCOUNT;


DROP TABLE CLIENT_DISCOUNT;

INSERT INTO CLIENT_DISCOUNT (DCODE_CLIENT, RATE) VALUES('C01', 0);
INSERT INTO CLIENT_DISCOUNT (DCODE_CLIENT, RATE) VALUES('C02', 0.03);
INSERT INTO CLIENT_DISCOUNT (DCODE_CLIENT, RATE) VALUES('C03', 0.05);

