CREATE TABLE CONSTRACT_GOODS(
  SEQ NUMBER PRIMARY KEY,
  CT_CODE VARCHAR2(20) NOT NULL,
  G_CODE VARCHAR2(20) NOT NULL,
  G_NAME VARCHAR2(100) NOT NULL,
  G_PRICE NUMBER NOT NULL,
  DU_CNT NUMBER,
  CONSTRAINT "CT_CODE_goods_FK" FOREIGN KEY ("CT_CODE") REFERENCES CONTRACT("CT_CODE")
);
 ALTER TABLE CONSTRACT_GOODS ADD CONSTRAINT G_CODE
    FOREIGN KEY (G_CODE) REFERENCES INVENTORY_GOODS(G_CODE);
 
SELECT * FROM CONTRACT_GOODS;

DROP TABLE CONSTRACT_GOODS;

CREATE SEQUENCE CONTRACT_GOODS_SEQ INCREMENT BY 1 START WITH 1;
