CREATE TABLE GOODS_DISCOUNT(
  DCODE_GOODS VARCHAR2(20) PRIMARY KEY,
  RATE NUMBER NOT NULL
);
 
 
SELECT * FROM GOODS_DISCOUNT;

DROP TABLE GOODS_DISCOUNT;

INSERT INTO GOODS_DISCOUNT (DCODE_GOODS, RATE) VALUES('G01', 0);
INSERT INTO GOODS_DISCOUNT (DCODE_GOODS, RATE) VALUES('G02', 0.03);

