CREATE TABLE LOCATION(
	AREA_CODE VARCHAR2(10) NOT NULL
	PRIMARY KEY
	,
	AREA VARCHAR2(10)
);

SELECT * FROM LOCATION;

DROP TABLE LOCATION;

INSERT INTO LOCATION
(AREA_CODE, AREA)
VALUES('LC01', '서울');

INSERT INTO LOCATION
(AREA_CODE, AREA)
VALUES('LC02', '대구');

INSERT INTO LOCATION
(AREA_CODE, AREA)
VALUES('LC03', '울산');

INSERT INTO LOCATION
(AREA_CODE, AREA)
VALUES('LC04', '부산');

INSERT INTO LOCATION
(AREA_CODE, AREA)
VALUES('LC05', '춘천');

INSERT INTO LOCATION
(AREA_CODE, AREA)
VALUES('LC06', '천안');

INSERT INTO LOCATION
(AREA_CODE, AREA)
VALUES('LC07', '대전');

INSERT INTO LOCATION
(AREA_CODE, AREA)
VALUES('LC08', '광주');