--공지게시판
CREATE TABLE BOARD(
  SEQ NUMBER PRIMARY KEY,  
  EMP_CODE VARCHAR2(10),
  TITLE VARCHAR2(100) NOT NULL,
  CONTENT VARCHAR2(4000) NOT NULL,
  REGDATE DATE NOT NULL,
  S_COUNT NUMBER NOT NULL,
  POST_DATE DATE NOT NULL,
  POST_USE VARCHAR2(5) NOT NULL,
  CONSTRAINT "BOARD_FK" FOREIGN KEY ("EMP_CODE") REFERENCES USER_INFO("EMP_CODE")
);

CREATE SEQUENCE BOARD_SEQ INCREMENT BY 1 START WITH 1;

--거래처
CREATE TABLE CLIENT(
  CLI_NUM VARCHAR2(100) PRIMARY KEY,
  EMP_CODE VARCHAR2(10),
  CLI_NAME VARCHAR2(100) NOT NULL,
  CLI_ADDR VARCHAR2(500) NOT NULL,
  CLI_TEL VARCHAR2(20) NOT NULL,
  CLI_AREA VARCHAR2(20) NOT NULL,
  CONSTRAINT "CLIENT_USER_FK" FOREIGN KEY ("EMP_CODE") REFERENCES USER_INFO("EMP_CODE")
);


--거래처할인
CREATE TABLE CLIENT_DISCOUNT(
	DCODE_CLIENT VARCHAR2(20) PRIMARY KEY,
	RATE NUMBER NOT NULL
);
INSERT INTO CLIENT_DISCOUNT (DCODE_CLIENT, RATE) VALUES('C01', 0);
INSERT INTO CLIENT_DISCOUNT (DCODE_CLIENT, RATE) VALUES('C02', 0.03);
INSERT INTO CLIENT_DISCOUNT (DCODE_CLIENT, RATE) VALUES('C03', 0.05);


--계약
CREATE TABLE CONTRACT(
  CT_CODE VARCHAR2(20) PRIMARY KEY,
  CTM_CODE VARCHAR2(20) NOT NULL,
  DCODE_CLIENT VARCHAR2(20),
  DU_PRICE NUMBER NOT NULL,
  DU_DATE DATE NOT NULL,
  CT_START DATE NOT NULL,
  CT_END DATE NOT NULL,
  CONSTRAINT "CON_CTM_CODE_FK" FOREIGN KEY ("CTM_CODE") REFERENCES CONTRACT_MANAGEMENT("CTM_CODE"),
  CONSTRAINT "CON_DCODE_CLIENT_FK" FOREIGN KEY ("DCODE_CLIENT") REFERENCES CLIENT_DISCOUNT("DCODE_CLIENT")
);

--계약관리
CREATE TABLE CONTRACT_MANAGEMENT(
  CTM_CODE VARCHAR2(20) PRIMARY KEY,
  CLI_NUM VARCHAR2(100),
  CONSTRAINT "CLI_NUM_FK" FOREIGN KEY ("CLI_NUM") REFERENCES CLIENT("CLI_NUM")
);
 
CREATE SEQUENCE CONTRACT_MANAGEMENT_SEQ INCREMENT BY 1 START WITH 1;


--상품할인
CREATE TABLE GOODS_DISCOUNT(
  DCODE_GOODS VARCHAR2(20) PRIMARY KEY,
  RATE NUMBER NOT NULL
);

INSERT INTO GOODS_DISCOUNT (DCODE_GOODS, RATE) VALUES('G01', 0);
INSERT INTO GOODS_DISCOUNT (DCODE_GOODS, RATE) VALUES('G02', 0.03);


--재고상품
CREATE TABLE INVENTORY_GOODS(
  G_CODE VARCHAR2(20) PRIMARY KEY,
  DCODE_GOODS VARCHAR2(20),
  G_NAME VARCHAR2(100) NOT NULL,
  IV_CNT NUMBER,
  G_KG VARCHAR2(10) NOT NULL,
  G_COUNTRY VARCHAR2(30) NOT NULL,
  G_CONTENT VARCHAR2(30) NOT NULL,
  G_AMOUNT VARCHAR2(10) NOT NULL,
  CONSTRAINT "INVENTORY_GOODS_FK" FOREIGN KEY ("DCODE_GOODS") REFERENCES GOODS_DISCOUNT("DCODE_GOODS")
);

--재고관리
CREATE TABLE INVENTORY_MANAGEMENT(
  SEQ NUMBER PRIMARY KEY,
  EMP_CODE VARCHAR2(10),
  G_CODE VARCHAR2(20) NOT NULL,
  G_NAME VARCHAR2(100) NOT NULL,
  IN_DATE DATE NOT NULL,
  IN_CNT NUMBER,
  CONSTRAINT "G_CODE_FK" FOREIGN KEY ("G_CODE") REFERENCES INVENTORY_GOODS("G_CODE"),
  CONSTRAINT "EMP_CODE_FK" FOREIGN KEY ("EMP_CODE") REFERENCES USER_INFO("EMP_CODE")
);
 
CREATE SEQUENCE INVENMANAGE_SEQ INCREMENT BY 1 START WITH 1;


--위치
CREATE TABLE LOCATION(
	AREA_CODE VARCHAR2(10) NOT NULL
	PRIMARY KEY
	,
	AREA VARCHAR2(10)
);

