SELECT * FROM ANSWERBOARD a 
ORDER BY "REF" DESC, STEP  ;

--UPDATE--
UPDATE  ANSWERBOARD  SET STEP = STEP +1
WHERE REF = (SELECT REF FROM ANSWERBOARD a WHERE SEQ='13')
AND STEP > (SELECT STEP FROM ANSWERBOARD a2 WHERE SEQ='13');

--INSERT--
INSERT INTO ANSWERBOARD (SEQ, ID, TITLE, CONTENT, "REF", STEP, "DEPTH")
VALUES(ANSWERBOARD_SEQ.NEXTVAL, 'ID', 'TITLE', 'CONTENT', 
(SELECT "REF" FROM ANSWERBOARD a WHERE SEQ='13'),
(SELECT STEP FROM ANSWERBOARD a2 WHERE SEQ='13')+1,
(SELECT "DEPTH" FROM ANSWERBOARD a3 WHERE SEQ='13')+1);


SELECT * FROM USERINFO u ;