-- 샘플데이터 입력하기
INSERT INTO GD.SPRINGBOARD
(SEQ, ID, TITLE, CONTENT, STEP, "DEPTH", REFER, READCOUNT, DELFLAG, REGDATE)
VALUES(SPRINGBOARD_SEQ.NEXTVAL, 'ADMIN', '스프링 보드', '스프링 보드입니다..', 0, 0, 
		(SELECT NVL(MAX(REFER),0) FROM SPRINGBOARD s)+1, 0, 'N', SYSDATE);

-- 새글 쓰기

INSERT INTO GD.SPRINGBOARD
(SEQ, ID, TITLE, CONTENT, STEP, "DEPTH", REFER, READCOUNT, DELFLAG, REGDATE)
VALUES(SPRINGBOARD_SEQ.NEXTVAL, 'ADMIN', '스프링 새글 입니다.', '스프링 새글 내용입니다.', 0, 0, 
		(SELECT NVL(MAX(REFER),0) FROM SPRINGBOARD s)+1, 0, 'N', SYSDATE);

	
--답글 쓰기(업데이트, 답글입력 Transaction)
UPDATE  SPRINGBOARD SET STEP = STEP +1
WHERE REFER = (SELECT REFER FROM SPRINGBOARD s WHERE SEQ='1')
AND STEP > (SELECT STEP FROM SPRINGBOARD s2 WHERE SEQ='1');

INSERT INTO GD.SPRINGBOARD
(SEQ, ID, TITLE, CONTENT, STEP, "DEPTH", REFER, READCOUNT, DELFLAG, REGDATE)
VALUES(SPRINGBOARD_SEQ.NEXTVAL, 'USER', '답글제목', '답글내용'
		,(SELECT STEP+1 FROM SPRINGBOARD s2 WHERE SEQ='1')
		,(SELECT "DEPTH"+1 FROM SPRINGBOARD s3 WHERE SEQ='1')
		,(SELECT REFER FROM SPRINGBOARD s WHERE SEQ='1')
		, 0, 'N', SYSDATE);
		
-- 상세글 보기
SELECT SEQ, ID, TITLE, CONTENT, READCOUNT, REGDATE 
	FROM SPRINGBOARD s 
		WHERE SEQ = '2';

--조회수(상세조회와 동시 진행)
UPDATE SPRINGBOARD 
	SET READCOUNT = READCOUNT+1
		WHERE SEQ = '2';

-- 글수정 
UPDATE SPRINGBOARD 
	SET TITLE = '수정된 제목', CONTENT = '수정 내용'
		WHERE SEQ = '2';


	
--글삭제 update 
UPDATE SPRINGBOARD  SET DELFLAG ='Y' WHERE DELFLAG='N' AND SEQ = '3';

-- 글삭제 delete
DELETE FROM SPRINGBOARD WHERE SEQ = '3';


-- 게시글 전체조회(삭제된글을 볼수있는 관리자와 아닌 사용자로 나뉨 , test는 LPAD로 작성 (dao는 그냥작성))
--LPAD 게시글 전체조회

SELECT SEQ, ID, LPAD(' ', "DEPTH"*3) || TITLE AS TITLE, STEP, "DEPTH" , REFER, READCOUNT, DELFLAG, REGDATE
	FROM SPRINGBOARD s
		ORDER BY REFER DESC, STEP;

SELECT SEQ, ID, LPAD(' ', "DEPTH"*3) || TITLE AS TITLE, STEP, "DEPTH" , REFER, READCOUNT, DELFLAG, REGDATE
	FROM SPRINGBOARD s
	WHERE DELFLAG='N'
		ORDER BY REFER DESC, STEP;


--하위 삭제 대상 찾기
SELECT SEQ, ID, TITLE, STEP, "DEPTH" , REFER, READCOUNT, DELFLAG, REGDATE
	FROM SPRINGBOARD s
	WHERE REFER = (SELECT REFER FROM SPRINGBOARD WHERE SEQ='2')
	ORDER BY REFER DESC, STEP;
	
SELECT RM, ID, NAME, EMAIL, AUTH, DELFLAG, REGDATE 
	FROM (
		SELECT ROW_NUMBER() OVER(ORDER BY DELFLAG DESC, REGDATE) RM,ID, NAME, EMAIL, AUTH, DELFLAG, REGDATE
		FROM SPRINGMEMBER s 
	)
	WHERE RM BETWEEN 1 AND 100;
	
SELECT ROW_NUMBER() OVER(ORDER BY DELFLAG DESC, REGDATE) RM,ID, NAME, EMAIL, AUTH, DELFLAG, REGDATE
		FROM SPRINGMEMBER s; 

