SELECT *
FROM JOBS;

INSERT INTO GD.JOBS
(JOB_ID, JOB_TITLE, MIN_SALARY, MAX_SALARY, USEAGE)
VALUES('1', '1', 1, 2,'Y');


DROP TABLE JOBS ;
-- GD.JOBS definition

UPDATE JOBS
SET USEAGE='Y';


CREATE TABLE "JOBS" 
   (   "JOB_ID" VARCHAR2(10), 
   "JOB_TITLE" VARCHAR2(35) NOT NULL ENABLE, 
   "MIN_SALARY" NUMBER(6,0), 
   "MAX_SALARY" NUMBER(6,0), 
   "USEAGE" VARCHAR2(5),
    CONSTRAINT "JOB_ID_PK" PRIMARY KEY ("JOB_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GD"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DB";

CREATE UNIQUE INDEX "JOB_ID_PK" ON "JOBS" ("JOB_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DB" ;
  
---
INSERT INTO GD.JOBS (JOB_ID,JOB_TITLE,MIN_SALARY,MAX_SALARY,USEAGE) VALUES ('AD_PRES','President',20000,40000,'Y');
INSERT INTO GD.JOBS (JOB_ID,JOB_TITLE,MIN_SALARY,MAX_SALARY,USEAGE) VALUES ('AD_VP','Administration Vice President',15000,30000,'Y');
INSERT INTO GD.JOBS (JOB_ID,JOB_TITLE,MIN_SALARY,MAX_SALARY,USEAGE) VALUES ('AD_ASST','Administration Assistant',3000,6000,'Y');
INSERT INTO GD.JOBS (JOB_ID,JOB_TITLE,MIN_SALARY,MAX_SALARY,USEAGE) VALUES ('FI_MGR','Finance Manager',8200,16000,'Y');
INSERT INTO GD.JOBS (JOB_ID,JOB_TITLE,MIN_SALARY,MAX_SALARY,USEAGE) VALUES ('FI_ACCOUNT','Accountant',4200,9000,'Y');
INSERT INTO GD.JOBS (JOB_ID,JOB_TITLE,MIN_SALARY,MAX_SALARY,USEAGE) VALUES ('AC_MGR','Accounting Manager',8200,16000,'Y');
INSERT INTO GD.JOBS (JOB_ID,JOB_TITLE,MIN_SALARY,MAX_SALARY,USEAGE) VALUES ('AC_ACCOUNT','Public Accountant',4200,9000,'Y');
INSERT INTO GD.JOBS (JOB_ID,JOB_TITLE,MIN_SALARY,MAX_SALARY,USEAGE) VALUES ('SA_MAN','Sales Manager',10000,20000,'Y');
INSERT INTO GD.JOBS (JOB_ID,JOB_TITLE,MIN_SALARY,MAX_SALARY,USEAGE) VALUES ('SA_REP','Sales Representative',6000,12000,'Y');
INSERT INTO GD.JOBS (JOB_ID,JOB_TITLE,MIN_SALARY,MAX_SALARY,USEAGE) VALUES ('PU_MAN','Purchasing Manager',8000,15000,'Y');
INSERT INTO GD.JOBS (JOB_ID,JOB_TITLE,MIN_SALARY,MAX_SALARY,USEAGE) VALUES ('PU_CLERK','Purchasing Clerk',2500,5500,'Y');
INSERT INTO GD.JOBS (JOB_ID,JOB_TITLE,MIN_SALARY,MAX_SALARY,USEAGE) VALUES ('ST_MAN','Stock Manager',5500,8500,'Y');
INSERT INTO GD.JOBS (JOB_ID,JOB_TITLE,MIN_SALARY,MAX_SALARY,USEAGE) VALUES ('ST_CLERK','Stock Clerk',2000,5000,'Y');
INSERT INTO GD.JOBS (JOB_ID,JOB_TITLE,MIN_SALARY,MAX_SALARY,USEAGE) VALUES ('SH_CLERK','Shipping Clerk',2500,5500,'Y');
INSERT INTO GD.JOBS (JOB_ID,JOB_TITLE,MIN_SALARY,MAX_SALARY,USEAGE) VALUES ('IT_PROG','개발자',100000,10000,'Y');
INSERT INTO GD.JOBS (JOB_ID,JOB_TITLE,MIN_SALARY,MAX_SALARY,USEAGE) VALUES ('MK_MAN','Marketing Manager',9000,15000,'Y');
INSERT INTO GD.JOBS (JOB_ID,JOB_TITLE,MIN_SALARY,MAX_SALARY,USEAGE) VALUES ('MK_REP','Marketing Representative',4000,9000,'Y');
INSERT INTO GD.JOBS (JOB_ID,JOB_TITLE,MIN_SALARY,MAX_SALARY,USEAGE) VALUES ('HR_REP','Human Resources Representative',4000,9000,'Y');
INSERT INTO GD.JOBS (JOB_ID,JOB_TITLE,MIN_SALARY,MAX_SALARY,USEAGE) VALUES ('IT_GOO','it programmer',1000,10000,'Y');
INSERT INTO GD.JOBS (JOB_ID,JOB_TITLE,MIN_SALARY,MAX_SALARY,USEAGE) VALUES ('IT','Developer',1000,2000,'Y');