SELECT * FROM USERinfo;

SELECT ID, NAME, PASSWORD, EMAIL, AUTH, DELFLAG, JOINDATE
FROM USERINFO
WHERE EMAIL=#{email} AND PASSWORD=#{password};

INSERT INTO GD.USERINFO
(ID, NAME, PASSWORD, EMAIL, AUTH, DELFLAG, JOINDATE)
VALUES(#{id}, #{id}, #{id}, #{id}, #{id}, #{id}, SYSDATE);



