
--로그인
SELECT EMP_PW, EMP_AUTH
FROM USER_INFO;
--아이디 중복 체크
SELECT COUNT(*)
FROM USER_INFO
WHERE EMP_CODE='SYS_45282';


--사용자계정등록
INSERT INTO USER_INFO
(EMP_CODE, AREA_CODE, EMP_NAME, EMP_PW, EMP_GENDER, EMP_USE, EMP_IMG,EMP_AUTH)
VALUES('CAD_33873', 'LC01', '이인환', 'inhwan1234', '남자', 'Y', EMPTY_BLOB(),'ADMIN');
--사용자 계정 수정
UPDATE USER_INFO
SET AREA_CODE='LC01', EMP_NAME='이인환', EMP_PW='inhwan1234', EMP_GENDER='남자', EMP_USE='Y', EMP_IMG=EMPTY_BLOB() 
WHERE EMP_CODE='CAD_33873';
--사용자 계정 삭제
DELETE FROM USER_INFO
WHERE EMP_CODE='CAD_33873';
--사용자 전체 조회
SELECT EMP_CODE, l.AREA , EMP_NAME, EMP_GENDER, CASE WHEN EMP_USE='Y' THEN '계정활성화' ELSE '계정 비활성화' END AS EMP_USE, EMP_IMG
FROM USER_INFO
LEFT JOIN LOCATION l
USING (AREA_CODE)
WHERE EMP_AUTH!='SYSTEM';
--사용자 이름으로 조회
SELECT EMP_CODE, l.AREA , EMP_NAME, EMP_GENDER, CASE WHEN EMP_USE='Y' THEN '계정활성화' ELSE '계정 비활성화' END AS EMP_USE, EMP_IMG
FROM USER_INFO
LEFT JOIN LOCATION l
USING (AREA_CODE)
WHERE EMP_AUTH!='SYSTEM'
AND EMP_NAME='이인환';


--재고현황 전체조회
SELECT * FROM INVENTORY_GOODS ig ;
--재고현황 상품명으로 조회
SELECT * FROM INVENTORY_GOODS ig WHERE G_NAME='케냐AA';
--입고현황 전체조회
SELECT * FROM INVENTORY_MANAGEMENT im ;
--입고현황 최근순
SELECT * FROM INVENTORY_MANAGEMENT im ORDER BY IN_DATE DESC;
--입고현황 오래된순
SELECT * FROM INVENTORY_MANAGEMENT im ORDER BY IN_DATE;

--통계 : (공통) 꺽은선로 현재 계약중인 거래처의 갯수 ,분기별 통계 조회(월별, 연도별(2년)) 
--(공통) 파이차트로 상품별 판매량으로 분기별 통계 조회(월별, 연도별(2년)) 
--(공통) 버블 차트 지역별 계약 건수(월별, 연도별(2년)) 
SELECT COUNT(cm.CLI_NUM)
FROM CONTRACT c 
JOIN CONTRACT_MANAGEMENT cm 
ON c.CTM_CODE = cm.CTM_CODE 
WHERE '2020-01-01' > c.CT_START 
AND '2020-01-01' < c.CT_END;

SELECT 
    TO_CHAR(TO_DATE('20200101_160000', 'YYYYMMDD_HH24MISS') - (INTERVAL '6' HOUR), 'YYYYMMDD') as DAY,
    TO_CHAR(NEXT_DAY(TO_DATE('20200101_160000', 'YYYYMMDD_HH24MISS'), 1) - 21 - INTERVAL '6' HOUR, 'YYYY-IW') as WEEK,
    TO_CHAR(TO_DATE('20200101_160000', 'YYYYMMDD_HH24MISS') - (INTERVAL '6' HOUR), 'YYYY-MM') as MONTH,
    TO_CHAR(TO_DATE('20200101_160000', 'YYYYMMDD_HH24MISS') - (INTERVAL '6' HOUR), 'YYYY-Q') as QUARTER
    FROM DUAL;
