-- 샘플 데이터 입력
INSERT INTO GD.SPRINGMEMBER
(ID, PW, AUTH, DELFLAG, REGDATE)
VALUES('ADMIN', '1234', 'A', 'N', SYSDATE);

INSERT INTO GD.SPRINGMEMBER
(ID, PW, AUTH, DELFLAG, REGDATE)
VALUES('USER', '1234', 'U', 'N', SYSDATE);

--회원 전체 조회 (등록일순 내림차순)
SELECT ID, AUTH, DELFLAG , REGDATE 
	FROM SPRINGMEMBER s 
		WHERE AUTH = 'U'
		ORDER BY REGDATE DESC;

--회원가입
INSERT INTO GD.SPRINGMEMBER
(ID, PW, AUTH, DELFLAG, REGDATE)
VALUES('ADMIN', '1234', 'A', 'N', SYSDATE);

--로그인
SELECT COUNT(ID)
	FROM SPRINGMEMBER s 
		WHERE ID='USER' AND PW = '1234'
		AND DELFLAG = 'N';
		
-- 비밀번호 확인
SELECT PW 
	FROM SPRINGMEMBER s 
		WHERE ID = 'USER';

