SELECT * FROM CONTRACT_MANAGEMENT cm ,GOODS g ;
   

SELECT DISTINCT G_CODE,G_NAME , G_PRICE  FROM CONSTRACT_GOODS cg ;
SELECT * FROM (SELECT CT_CODE  FROM CONTRACT c),(SELECT DISTINCT G_CODE,G_NAME , G_PRICE  FROM CONSTRACT_GOODS cg);