-- 자세 테이블
CREATE TABLE POSTURE(
	POS_SEQ NUMBER NOT NULL,
	POS_TYPE VARCHAR2(30) NOT NULL,
	POS_TIME DATE NOT NULL,
	POS_COUNT NUMBER NOT NULL,
	MB_ID VARCHAR2(30) NOT NULL,
	CONSTRAINT "POSTURE_PK" PRIMARY KEY(POS_SEQ)
);
CREATE SEQUENCE POSTURE_SEQ START WITH 1 INCREMENT BY 1;

SELECT * FROM POSTURE p ;

INSERT INTO GD.POSTURE
(POS_SEQ,POS_TYPE, POS_TIME, POS_COUNT, MB_ID)
VALUES(POSTURE_SEQ.NEXTVAL,'거북목', '2022-05-06', 10, 'hwan');


INSERT INTO GD.POSTURE
(POS_SEQ,POS_TYPE, POS_TIME, POS_COUNT, MB_ID)
VALUES(POSTURE_SEQ.NEXTVAL,'거북목', '2022-05-07', 20, 'hwan');
INSERT INTO GD.POSTURE
(POS_SEQ,POS_TYPE, POS_TIME, POS_COUNT, MB_ID)
VALUES(POSTURE_SEQ.NEXTVAL,'거북목', '2022-05-08', 30, 'hwan');
INSERT INTO GD.POSTURE
(POS_SEQ,POS_TYPE, POS_TIME, POS_COUNT, MB_ID)
VALUES(POSTURE_SEQ.NEXTVAL,'거북목', '2022-05-09', 24, 'hwan');
INSERT INTO GD.POSTURE
(POS_SEQ,POS_TYPE, POS_TIME, POS_COUNT, MB_ID)
VALUES(POSTURE_SEQ.NEXTVAL,'거북목', '2022-05-10', 50, 'hwan');
INSERT INTO GD.POSTURE
(POS_SEQ,POS_TYPE, POS_TIME, POS_COUNT, MB_ID)
VALUES(POSTURE_SEQ.NEXTVAL,'거북목', '2022-05-11', 33, 'hwan');
INSERT INTO GD.POSTURE
(POS_SEQ,POS_TYPE, POS_TIME, POS_COUNT, MB_ID)
VALUES(POSTURE_SEQ.NEXTVAL,'거북목', '2022-05-12', 22, 'hwan');
INSERT INTO GD.POSTURE
(POS_SEQ,POS_TYPE, POS_TIME, POS_COUNT, MB_ID)
VALUES(POSTURE_SEQ.NEXTVAL,'거북목', '2022-05-13', 33, 'hwan');

SELECT POS_SEQ, POS_TYPE , TO_CHAR(POS_TIME,'yyyy-mm-dd') POS_TIME  , POS_COUNT , MB_ID  FROM POSTURE p 
WHERE POS_TYPE ='거북목'
AND POS_TIME < TO_CHAR(SYSDATE,'yyyy-mm-dd')
AND POS_TIME > TO_CHAR(SYSDATE-7,'yyyy-mm-dd')
ORDER BY POS_TIME;