CREATE TABLE USERINFO(     NAME VARCHAR2(15) NOT NULL,     ID    VARCHAR2(30) NOT NULL,   
PASSWORD VARCHAR2(50) NOT NULL,     AUTH CHAR(1) DEFAULT 'U' );

ALTER TABLE USERINFO  ADD CONSTRAINT USERINFO_PK PRIMARY KEY (ID);

SELECT * FROM userinfo;
